In [2]:
import numpy as np

In [3]:
arr = np.array([1,4,9,16,25])
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


In [4]:
print(np.exp(arr))

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [5]:
print(np.exp(2))

7.38905609893065


In [6]:
print(np.log(arr))

[0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
print(np.sum(arr))

21


In [9]:
print("每列总和",np.sum(arr,axis=0))

每列总和 [5 7 9]


In [10]:
print("每列总和",np.sum(arr,axis=1))

每列总和 [ 6 15]


In [11]:
print(np.std(arr))

1.707825127659933


In [12]:
print(np.var(arr))

2.9166666666666665


In [13]:
a = np.array([[1], [2], [3]])  # 形状 (3, 1)
b = np.array([10, 20, 30])     # 形状 (3,)

print("a + b:\n", a + b)

a + b:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [14]:
data = np.random.normal(100, 15, 20)  # 均值100，标准差15
print("原始数据:", data)

原始数据: [ 89.99018789  92.79850532 106.40349465  89.11985861 120.20194941
 111.98068904  68.67890453  77.69352788  88.54231709 111.43202271
 115.92016256 111.81625833 139.89924764  85.8411348  103.05289521
  73.18400992  99.76546628 114.08900427  88.22078625  77.58740264]


In [15]:
A = np.array([[4, 7], [2, 6]])
print("原矩阵 A:\n", A)

原矩阵 A:
 [[4 7]
 [2 6]]


In [18]:
# 求逆矩阵
A_inv = np.linalg.inv(A)
print("逆矩阵 A⁻¹:\n", A_inv)

# 验证 A × A⁻¹ = 单位矩阵
identity = A @ A_inv
print("A × A⁻¹ (应该接近单位矩阵):\n", np.round(identity))

逆矩阵 A⁻¹:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A × A⁻¹ (应该接近单位矩阵):
 [[ 1.  0.]
 [-0.  1.]]


In [19]:
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print("矩阵 A:\n", A)
print("行列式 det(A):", det_A)

矩阵 A:
 [[1 2]
 [3 4]]
行列式 det(A): -2.0000000000000004


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 随机选择一个元素
choice = np.random.choice(data)
print("随机选择:", choice)

# 随机选择多个元素 (无放回)
choices_no_replace = np.random.choice(data, size=3, replace=False)
print("无放回抽样:", choices_no_replace)