In [2]:
 numpy as np

In [3]:
arr = np.array([1,4,9,16,25])
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


In [4]:
print(np.exp(arr))

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [5]:
print(np.exp(2))

7.38905609893065


In [6]:
print(np.log(arr))

[0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
print(np.sum(arr))

21


In [9]:
print("每列总和",np.sum(arr,axis=0))

每列总和 [5 7 9]


In [10]:
print("每列总和",np.sum(arr,axis=1))

每列总和 [ 6 15]


In [11]:
print(np.std(arr))

1.707825127659933


In [12]:
print(np.var(arr))

2.9166666666666665


In [13]:
a = np.array([[1], [2], [3]])  # 形状 (3, 1)
b = np.array([10, 20, 30])     # 形状 (3,)

print("a + b:\n", a + b)

a + b:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [14]:
data = np.random.normal(100, 15, 20)  # 均值100，标准差15
print("原始数据:", data)

原始数据: [ 89.99018789  92.79850532 106.40349465  89.11985861 120.20194941
 111.98068904  68.67890453  77.69352788  88.54231709 111.43202271
 115.92016256 111.81625833 139.89924764  85.8411348  103.05289521
  73.18400992  99.76546628 114.08900427  88.22078625  77.58740264]


In [15]:
A = np.array([[4, 7], [2, 6]])
print("原矩阵 A:\n", A)

原矩阵 A:
 [[4 7]
 [2 6]]


In [18]:
# 求逆矩阵
A_inv = np.linalg.inv(A)
print("逆矩阵 A⁻¹:\n", A_inv)

# 验证 A × A⁻¹ = 单位矩阵
identity = A @ A_inv
print("A × A⁻¹ (应该接近单位矩阵):\n", np.round(identity))

逆矩阵 A⁻¹:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A × A⁻¹ (应该接近单位矩阵):
 [[ 1.  0.]
 [-0.  1.]]


In [19]:
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print("矩阵 A:\n", A)
print("行列式 det(A):", det_A)

矩阵 A:
 [[1 2]
 [3 4]]
行列式 det(A): -2.0000000000000004


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 随机选择一个元素
choice = np.random.choice(data)
print("随机选择:", choice)

# 随机选择多个元素 (无放回)
choices_no_replace = np.random.choice(data, size=3, replace=False)
print("无放回抽样:", choices_no_replace)

In [2]:
import pandas as pd
import numpy as np
s1 = pd.Series([1, 3, 5, np.nan, 6, 8])
print("从列表创建:\n", s1)

从列表创建:
 0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [3]:
# 从字典创建（键成为索引）
s2 = pd.Series({'a': 1, 'b': 3, 'c': 5})
print("从字典创建:\n", s2)

从字典创建:
 a    1
b    3
c    5
dtype: int64


In [12]:
s3 : pd.core.series.Series= pd.Series([10, 20, 30], index=['x', 'y', 'z'])
print("指定索引:\n", s3)
s2 = pd.Series({'a': 1, 'b': 3, 'c': 5})
print("从字典创建:\n", s2)

# 指定索引
s3 = pd.Series([10, 20, 30], index=['x', 'y', 'z'])
print("指定索引:\n", s3)

指定索引:
 x    10
y    20
z    30
dtype: int64
从字典创建:
 a    1
b    3
c    5
dtype: int64
指定索引:
 x    10
y    20
z    30
dtype: int64


In [13]:
# 基本属性
print("值:", s3.values)
print("索引:", s3.index)
print("数据类型:", s3.dtype)

# 索引访问
print("s3['x']:", s3['x'])  # 10
print("s3[0]:", s3[0])      # 10

# 向量化运算
print("s3 * 2:\n", s3 * 2)
print("s3 > 15:\n", s3 > 15)

值: [10 20 30]
索引: Index(['x', 'y', 'z'], dtype='object')
数据类型: int64
s3['x']: 10
s3[0]: 10
s3 * 2:
 x    20
y    40
z    60
dtype: int64
s3 > 15:
 x    False
y     True
z     True
dtype: bool


C:\Users\aurora\AppData\Local\Temp\ipykernel_320008\1261591997.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("s3[0]:", s3[0])      # 10


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])

# 选择大于3的元素
mask = arr > 3
print("掩码:", mask)
print(type(mask))# [False False False  True  True  True]
print("大于3的元素:", arr[mask])  # [4 5 6]

掩码: [False False False  True  True  True]
<class 'numpy.ndarray'>
大于3的元素: [4 5 6]


In [23]:
np_array = np.random.normal(0,1,(33, 22))
print(np_array)

[[ 1.03131998 -0.93354937  0.8322872   0.10446359  0.04679524 -2.43285412
   0.83532186  2.05944843  0.76296779  0.73497725  0.32735318 -0.96194889
   0.81032724 -1.34561634 -0.34839353 -0.27198356  0.19603581  0.76152131
  -2.53337081 -1.38653611  0.44349948  1.51780252]
 [-0.65311418  0.12457755 -1.26926887 -1.26234633 -1.88137604 -0.27763515
   1.30677152 -0.26280798 -0.61742435  1.36691417  0.920136    1.24862594
  -0.09224254  0.35559132  0.18654867 -0.03084346  0.27278386 -1.01631698
   0.48148983 -0.62413412 -0.73334111 -0.81735951]
 [ 1.19328804  0.60365326 -0.9724169   0.45423259  0.57990835  0.02623133
  -0.23525531  0.1177231   0.3564564  -0.4457694  -1.07927912  1.3999232
   0.17468625 -0.04462465 -0.29943686  1.0703195  -1.61515261  0.89076025
   0.23229331 -0.26062634 -0.38608608 -0.8246167 ]
 [-0.09346144  1.2786378   0.74743277  1.3408207  -1.11151693  0.79207905
   0.13612173  1.47207162 -0.39506572 -0.591959   -1.56185998 -0.23565671
  -0.74273991 -0.2183628   1.87778

In [27]:
print(np.mean(np_array))

0.013859552328115246


In [28]:
# 创建示例数据
df = pd.DataFrame({
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '年龄': [25, 30, 35, 28, 32],
    '城市': ['北京', '上海', '广州', '深圳', '北京'],
    '工资': [5000, 8000, 7000, 6000, 7500],
    '部门': ['技术', '销售', '技术', '人事', '销售']
})

print("前3行:")
print(df.head(3))

print("\n后2行:")
print(df.tail(2))

print("\n数据形状:", df.shape)
print("列名:", df.columns.tolist())
print("索引:", df.index.tolist())

前3行:
   姓名  年龄  城市    工资  部门
0  张三  25  北京  5000  技术
1  李四  30  上海  8000  销售
2  王五  35  广州  7000  技术

后2行:
   姓名  年龄  城市    工资  部门
3  赵六  28  深圳  6000  人事
4  钱七  32  北京  7500  销售

数据形状: (5, 5)
列名: ['姓名', '年龄', '城市', '工资', '部门']
索引: [0, 1, 2, 3, 4]


In [29]:
# 基本信息
print("数据类型:\n", df.dtypes)
print("\n基本信息:")
print(df.info())

print("\n描述性统计:")
print(df.describe())

print("\n唯一值:")
print("城市的唯一值:", df['城市'].unique())
print("城市的值计数:\n", df['城市'].value_counts())

数据类型:
 姓名    object
年龄     int64
城市    object
工资     int64
部门    object
dtype: object

基本信息:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   姓名      5 non-null      object
 1   年龄      5 non-null      int64 
 2   城市      5 non-null      object
 3   工资      5 non-null      int64 
 4   部门      5 non-null      object
dtypes: int64(2), object(3)
memory usage: 328.0+ bytes
None

描述性统计:
              年龄           工资
count   5.000000     5.000000
mean   30.000000  6700.000000
std     3.807887  1204.159458
min    25.000000  5000.000000
25%    28.000000  6000.000000
50%    30.000000  7000.000000
75%    32.000000  7500.000000
max    35.000000  8000.000000

唯一值:
城市的唯一值: ['北京' '上海' '广州' '深圳']
城市的值计数:
 城市
北京    2
上海    1
广州    1
深圳    1
Name: count, dtype: int64


In [30]:
# 按位置选择
print("第2行:\n", df.iloc[1])        # 单行
print("前3行:\n", df.iloc[0:3])      # 多行

# 按标签选择
print("按标签选择:\n", df.loc[0:2])   # 包含结束位置

# 布尔索引
high_salary = df[df['工资'] > 6000]
print("工资>6000的员工:\n", high_salary)

beijing_employees = df[df['城市'] == '北京']
print("北京员工:\n", beijing_employees)

第2行:
 姓名      李四
年龄      30
城市      上海
工资    8000
部门      销售
Name: 1, dtype: object
前3行:
    姓名  年龄  城市    工资  部门
0  张三  25  北京  5000  技术
1  李四  30  上海  8000  销售
2  王五  35  广州  7000  技术
按标签选择:
    姓名  年龄  城市    工资  部门
0  张三  25  北京  5000  技术
1  李四  30  上海  8000  销售
2  王五  35  广州  7000  技术
工资>6000的员工:
    姓名  年龄  城市    工资  部门
1  李四  30  上海  8000  销售
2  王五  35  广州  7000  技术
4  钱七  32  北京  7500  销售
北京员工:
    姓名  年龄  城市    工资  部门
0  张三  25  北京  5000  技术
4  钱七  32  北京  7500  销售


In [32]:
# 多条件选择
condition = (df['工资'] > 6000) & (df['年龄'] < 35)
selected = df[condition]
print("工资>6000且年龄<35:\n", selected)

# 使用query方法
selected2 = df.query('工资 > 6000 and 年龄 < 35')
print("使用query方法:\n", selected2)

# 包含特定值的筛选
tech_employees = df[df['部门'].str.contains('技术')]
print("技术部门员工:\n", tech_employees)
print(type(df['部门'].str))

工资>6000且年龄<35:
    姓名  年龄  城市    工资  部门
1  李四  30  上海  8000  销售
4  钱七  32  北京  7500  销售
使用query方法:
    姓名  年龄  城市    工资  部门
1  李四  30  上海  8000  销售
4  钱七  32  北京  7500  销售
技术部门员工:
    姓名  年龄  城市    工资  部门
0  张三  25  北京  5000  技术
2  王五  35  广州  7000  技术
<class 'pandas.core.strings.accessor.StringMethods'>


In [33]:
print(np_array)

[[ 1.03131998 -0.93354937  0.8322872   0.10446359  0.04679524 -2.43285412
   0.83532186  2.05944843  0.76296779  0.73497725  0.32735318 -0.96194889
   0.81032724 -1.34561634 -0.34839353 -0.27198356  0.19603581  0.76152131
  -2.53337081 -1.38653611  0.44349948  1.51780252]
 [-0.65311418  0.12457755 -1.26926887 -1.26234633 -1.88137604 -0.27763515
   1.30677152 -0.26280798 -0.61742435  1.36691417  0.920136    1.24862594
  -0.09224254  0.35559132  0.18654867 -0.03084346  0.27278386 -1.01631698
   0.48148983 -0.62413412 -0.73334111 -0.81735951]
 [ 1.19328804  0.60365326 -0.9724169   0.45423259  0.57990835  0.02623133
  -0.23525531  0.1177231   0.3564564  -0.4457694  -1.07927912  1.3999232
   0.17468625 -0.04462465 -0.29943686  1.0703195  -1.61515261  0.89076025
   0.23229331 -0.26062634 -0.38608608 -0.8246167 ]
 [-0.09346144  1.2786378   0.74743277  1.3408207  -1.11151693  0.79207905
   0.13612173  1.47207162 -0.39506572 -0.591959   -1.56185998 -0.23565671
  -0.74273991 -0.2183628   1.87778

In [35]:
print(np_array[0,0])

1.0313199773603754


In [36]:
# 创建包含缺失值的数据
df_nan = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [10, 20, 30, 40]
})

print("原始数据（含缺失值）:\n", df_nan)
print("\n缺失值统计:\n", df_nan.isnull().sum())

# 填充缺失值
df_filled = df_nan.fillna({'A': 0, 'B': df_nan['B'].mean()})
print("填充缺失值后:\n", df_filled)

# 删除缺失值
df_dropped_na = df_nan.dropna()
print("删除缺失值后:\n", df_dropped_na)

原始数据（含缺失值）:
      A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

缺失值统计:
 A    1
B    2
C    0
dtype: int64
填充缺失值后:
      A    B   C
0  1.0  5.0  10
1  2.0  6.5  20
2  0.0  6.5  30
3  4.0  8.0  40
删除缺失值后:
      A    B   C
0  1.0  5.0  10
3  4.0  8.0  40


In [37]:
print("数据类型:\n", df.dtypes)

# 转换数据类型
df['年龄'] = df['年龄'].astype('float64')
print("转换年龄类型后:\n", df.dtypes)

# 字符串操作
df['姓名大写'] = df['姓名'].str.upper()
df['城市长度'] = df['城市'].str.len()
print("字符串操作后:\n", df[['姓名', '姓名大写', '城市', '城市长度']])

数据类型:
 姓名    object
年龄     int64
城市    object
工资     int64
部门    object
dtype: object
转换年龄类型后:
 姓名     object
年龄    float64
城市     object
工资      int64
部门     object
dtype: object
字符串操作后:
    姓名 姓名大写  城市  城市长度
0  张三   张三  北京     2
1  李四   李四  上海     2
2  王五   王五  广州     2
3  赵六   赵六  深圳     2
4  钱七   钱七  北京     2


In [38]:
# 按单列分组
grouped_city = df.groupby('城市')
print("按城市分组后的平均工资:\n", grouped_city['工资'].mean())

# 按多列分组
grouped_multi = df.groupby(['城市', '部门'])
print("按城市和部门分组:\n", grouped_multi['工资'].mean())

按城市分组后的平均工资:
 城市
上海    8000.0
北京    6250.0
广州    7000.0
深圳    6000.0
Name: 工资, dtype: float64
按城市和部门分组:
 城市  部门
上海  销售    8000.0
北京  技术    5000.0
    销售    7500.0
广州  技术    7000.0
深圳  人事    6000.0
Name: 工资, dtype: float64


In [39]:
# 对同一列使用多个聚合函数
agg_result = df.groupby('城市')['工资'].agg(['mean', 'sum', 'count', 'std'])
print("各城市工资统计:\n", agg_result)

# 对不同列使用不同聚合函数
agg_result_multi = df.groupby('部门').agg({
    '工资': ['mean', 'max'],
    '年龄': ['min', 'max', 'mean']
})
print("各部门多指标统计:\n", agg_result_multi)

各城市工资统计:
       mean    sum  count          std
城市                                   
上海  8000.0   8000      1          NaN
北京  6250.0  12500      2  1767.766953
广州  7000.0   7000      1          NaN
深圳  6000.0   6000      1          NaN
各部门多指标统计:
         工资          年龄            
      mean   max   min   max  mean
部门                                
人事  6000.0  6000  28.0  28.0  28.0
技术  6000.0  7000  25.0  35.0  30.0
销售  7750.0  8000  30.0  32.0  31.0


In [40]:
# 创建数据透视表
pivot_table = df.pivot_table(
    values='工资',
    index='城市',
    columns='部门',
    aggfunc='mean',
    fill_value=0
)
print("数据透视表:\n", pivot_table)

# 多维度数据透视
pivot_multi = df.pivot_table(
    values='工资',
    index=['城市', '部门'],
    aggfunc=['mean', 'count']
)
print("多维度数据透视:\n", pivot_multi)

数据透视表:
 部门      人事      技术      销售
城市                        
上海     0.0     0.0  8000.0
北京     0.0  5000.0  7500.0
广州     0.0  7000.0     0.0
深圳  6000.0     0.0     0.0
多维度数据透视:
          mean count
           工资    工资
城市 部门              
上海 销售  8000.0     1
北京 技术  5000.0     1
   销售  7500.0     1
广州 技术  7000.0     1
深圳 人事  6000.0     1


In [41]:
# 创建第二个DataFrame
df2 = pd.DataFrame({
    '姓名': ['张三', '李四', '孙八'],
    '工龄': [3, 5, 2],
    '绩效': ['A', 'B', 'A']
})

print("df2:\n", df2)

# 内连接
merged_inner = pd.merge(df, df2, on='姓名', how='inner')
print("内连接结果:\n", merged_inner)

# 左连接
merged_left = pd.merge(df, df2, on='姓名', how='left')
print("左连接结果:\n", merged_left)

df2:
    姓名  工龄 绩效
0  张三   3  A
1  李四   5  B
2  孙八   2  A
内连接结果:
    姓名    年龄  城市    工资  部门 姓名大写  城市长度  工龄 绩效
0  张三  25.0  北京  5000  技术   张三     2   3  A
1  李四  30.0  上海  8000  销售   李四     2   5  B
左连接结果:
    姓名    年龄  城市    工资  部门 姓名大写  城市长度   工龄   绩效
0  张三  25.0  北京  5000  技术   张三     2  3.0    A
1  李四  30.0  上海  8000  销售   李四     2  5.0    B
2  王五  35.0  广州  7000  技术   王五     2  NaN  NaN
3  赵六  28.0  深圳  6000  人事   赵六     2  NaN  NaN
4  钱七  32.0  北京  7500  销售   钱七     2  NaN  NaN


In [44]:
# 垂直拼接（添加行）
new_employee = pd.DataFrame({
    '姓名': ['周九'],
    '年龄': [29],
    '城市': ['杭州'],
    '工资': [6500],
    '部门': ['技术']
})

df_appended = pd.concat([df, new_employee], ignore_index=False)
print("拼接后的数据:\n", df_appended)

拼接后的数据:
    姓名    年龄  城市    工资  部门 姓名大写  城市长度
0  张三  25.0  北京  5000  技术   张三   2.0
1  李四  30.0  上海  8000  销售   李四   2.0
2  王五  35.0  广州  7000  技术   王五   2.0
3  赵六  28.0  深圳  6000  人事   赵六   2.0
4  钱七  32.0  北京  7500  销售   钱七   2.0
0  周九  29.0  杭州  6500  技术  NaN   NaN
